server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://sql8.freesqldatabase.com:3306/sql8829417?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sql8829417}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:5UI2Srb2jF}

jwt.secret=${JWT_SECRET:gski39fak49g02so205054gjo103tfl2}
jwt.expiration=${JWT_EXPIRATION:86400000}

upload.base-path=${UPLOAD_BASE_PATH:uploads}
upload.base-url=${UPLOAD_BASE_URL:https://localbrew-localbrew.up.railway.app/uploads}

spring.jpa.hibernate.ddl-auto=create

# Upload immagini
upload.base-path=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
